debug_mode: false
seed: 0
input_dir: input
input_path: ''
output_dir: output
output_path: ''
device: ''
# dtype: float64

wandb:
  project: grokking_mnist

num_workers: 28

train:
  num_epochs: 20000
  batch_size: 200
  learning_rate: 0.001
  weight_decay: 0.01
  loss: ce
  label_smoothing: 0
  subset_size: 1000
  grad_norm: 1.0
  initialization_scale: 6

val:
  batch_size: 512

model: mlp
history: true

transformer:
  layers: 2
  width: 128
  heads: 4

mlp:
  hidden_dim: 200
  hidden_layers: 1
