debug_mode: false
seed: 0
input_dir: input
output_dir: output
save_model: true

wandb:
  project: grokking_adversarial

train:
  optimization_steps: 500000
  batch_size: 256
  optimizer: adamw
  learning_rate: 0.001
  weight_decay: 0.0
  loss: ce
  label_smoothing: 0
  subset_size: 50000
  grad_norm: 1.0

val:
  batch_size: 2048

local_complexity:
  compute_lc: true
  approx_n: 1024
  n_frame: 40
  r_frame: 0.005
  lc_batch_size: 256

adversarial:
  compute_robust: true
  atk_eps: ${fraction:"16/255"}
  atk_alpha: ${fraction:"4/255"}
  atk_epochs: 10
  dmax: 2.7537
  dmin: -2.4291

train_adv_samples:
  enable: false
  interrupt_step: 3500
  train_size: 1000

dataset:
  name: cifar-10
  format: ffcv
  num_classes: 10
  num_workers: 28

mnist:
  initialization_scale: 1

model: preact_resnet18

mlp:
  hidden_dim: 200
  hidden_layers: 1

resnet:
  bn: identity
